Dockerfile.openresty
Adds `--with-stream_realip_module` to OpenResty `configure` flags.
See also:
- https://github.com/Kong/kong/pull/4163
- https://github.com/Kong/homebrew-kong/pull/86
=> feat(openresty) compile nginx with stream_realip_module

Makefile, test/pytest.ini, test/run_tests.sh, test/test_plugin-key-auth.tavern.yaml, test/test_smoke.tavern.yaml
- added a convenience method to make developing functional tests easier
- tweaked the smoke test to delete the service and route that it creates
- added a functional test for key-auth plugin functionality
=> tests(key-auth) add key-auth plugin functional tests

.travis.yml, Dockerfile.openresty, Makefile
use travis-ci file cache to cache build layers associated with some key docker images. Speed improvements aren't that astounding but it will give more reproducible / reliable builds
=> chore(ci) setup travis-ci docker build layer cache

.travis.yml
early notification that there's build / CI breaking changes in Kong@next would be a nice to have but shouldn't explicitly fail the builds.
This adds builds of kong@next which are allowed to fail to travis-ci
=> chore(ci) build Kong@master as well as Kong@next branches

Dockerfile.openresty, Makefile, entrypoint.sh
Kong 1.1.0 is going to require libyaml to be installed
All four `next` builds fail
Now they pass
Needed to fix daily builds of [next](https://travis-ci.org/Kong/kong/builds/496104400)
=> fix(dependency) add libyaml dependency

README.md, test/test_plugin-request-termination.tavern.yaml
Test serviceless route that is using the request termination plugin.
This PR / branch will *not* pass until https://github.com/Kong/kong/pull/4286 is merged
=> test(request termination)

Dockerfile.kong, entrypoint.sh, install-lyaml.sh
building lyaml requires some trickery that is challenging to capture in a Dockerfile but can be handled in a separate bash script
=> chore(lyaml) cache the lyaml build result

Dockerfile.kong, entrypoint.sh
when building packages we configure and install to a temporary directory for the purposes of packaging ( `/tmp/build` ) but when the resulting package is installed on host systems it installs to `/`
This fix is specific to luarocks `3.1.2` which when installed with lua in `/tmp/build` will hold onto that piece of information even after being installed on a host system. Quickfix for this is to configure luarocks with the correct final location of lua by temporarily `cp -R /tmp/build/* /`
=> fix(luarocks) fix for luarocks 3.1.2 compilation issue

Makefile, test/build_container.sh, test/run_tests.sh, test/test_plugin-key-auth.tavern.yaml
This is needed so we can test custom Kong images. Plugins can build a custom tagged docker image and utilize kong build tools to functionally test said plugin
=> test(k8s-sidecar) make test setup more flexible

.travis.yml, Makefile, test/run_tests.sh
recreate the `make setup_tests` for backwards compatibility until we can migrate everything away from it.
make sure the kind k8s cluster is entirely ready before trying to begin the functional tests
=> fix(ci) make sure we wait until k8s is ready before running tests

.ci/setup_kind.sh
The v2.15.0 get_helm script doesn't know not to accidentally pull helm 3.0. Use `master` of `get_helm.sh` and use an environment variable to pin helm version
=> fix(helm) adjust how we pin the helm version

.rpmmacros, Dockerfile.package, Makefile, fpm-entrypoint.sh
To create signed rpm releases:
- replace kong.private.gpg-key.asc with a actual private key
- export PRIVATE_KEY_PASSPHRASE
Default behaviour if PRIVATE_KEY_PASSPHRASE isn't set we create a normal rpm package
```
make package-kong
rpm -K output/kong-1.4.0.el8.amd64.rpm
output/kong-1.4.0.el8.amd64.rpm: RSA sha1 ((MD5) PGP) md5 NOT OK (MISSING KEYS: (MD5) PGP#1d5f3726)
unset PRIVATE_KEY_PASSPHRASE
make package-kong
rpm -K output/kong-1.4.0.el8.amd64.rpm
output/kong-1.4.0.el8.amd64.rpm: sha1 md5 OK
```
=> feat(sign) setup rpm signing

Makefile
Cherry pick of #173 on release-2.0.
#173: fix(cache) adjust how we set docker cache
For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.
=> Automated cherry pick of #173: fix(cache) adjust how we set docker cache

.travis.yml, test/Dockerfile.rpm
RHEL6 full support ended on May 10, 2016, End of Maintenance Support 1 ended on May 10, 2017.
The RHEL 7 and RHEL 8 ubi images have the ability to install and test our Kong releases without requiring redhat credentials.
These two reasons are strong enough reasons that it's time to ditch rhel6
=> feat(rhel6) drop redhat 6 as a build option

Jenkinsfile
ec2 workers for building arm assets require a random element to their name. We were hitting an issue with branch and PR builds or kong-build-tools trying to make ec2 machines with the same name and one of the two will fail.
=> chore(ci) adjust arm build workers to include a random element to the machine name

Jenkinsfile, dockerfiles/Dockerfile.rpm
Centos and RHEL 8 builds started to fail with the following:
```
error: rpmdb: BDB0060 PANIC: fatal region error detected; run recovery
error: db5 error(-30973) from db->close: BDB0087 DB_RUNRECOVERY: Fatal error, run database recovery
```
=> fix(rpm) fix rpm builds

openresty-build-tools/kong-ngx-build
Stream lua-kong-nginx-module is no longer being built, causing Travis tests to fail unexpectedly.
=> Fix kong-ngx-build bugs

docker-compose.yml
Cherry pick of #222 on release-2.0.
#222: fix(postgres) postgres requires a password now
For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.
=> Automated cherry pick of #222: fix(postgres) postgres requires a password now

openresty-build-tools/kong-ngx-build
This PR contains fixes for 2 errors and 1 warning detected while trying to make kong-ngx-build runable from homebrew.
Strongly recommended to do another patch tag (3.1.3?) of kong-build-tools after merging.
=> fix(kong-ngx-build) mac fixes

openresty-build-tools/kong-ngx-build
So far it only supports either `master` or a branch. We need to be able to pin either versions or SHAs directly, if we want to pin this repo at all, which I think we do, since `master` won't work with all versions always
* Allow tags and SHAs for kong-ngx-module version
* Only include `/stream` if it is in there.
=> fix(build) support tags for kong-ngx-module

openresty-build-tools/kong-ngx-build
Quickfix for openssl moving releases around. The pattern substitution is not perfect, but works for now. A better regex could work, but would also fail in some cases, ie: `0.9.x`.
The other option is to get the release directly from github: https://github.com/openssl/openssl/releases . We would need then to translate `1.1.1c` -> `OpenSSL_1_1_1c`
=> fix(or-build-tools) fix openssl download 404

Makefile
The output of `wc -l` on mac osx has leading whitespaces, and hence this command hangs even when all 3 containers are `healthy`. This PR trims leading/trailing whitespaces.
=> fixes leading whitespaces in wc command on osx

test/tests/01-package/run.sh
this should have been pinned from the start. The fact that it wasn't is currently failing some builds
=> fix(systemd) pin the systemd ubuntu version

dockerfiles/Dockerfile.golang
fix so when running
```
go-pluginserver --version
```
it returns the actual go-pluginserver version not `development`
=> chore(go-pluginserver) small fix for go-pluginserver --version

openresty-patches/patches/1.15.8.3/nginx-1.15.8_01-upstream_client_certificate_and_ssl_verify.patch, openresty-patches/patches/1.15.8.3/nginx-1.15.8_03-stream_proxy_ssl_disable.patch, openresty-patches/patches/1.15.8.3/ngx_lua-0.10.15_01-cosocket-mtls.patch
Before this commit:
```
patching file LuaJIT-2.1-20190507/src/lj_tab.c
patching file LuaJIT-2.1-20190507/src/lj_asm_arm.h
patching file LuaJIT-2.1-20190507/src/lj_api.c
patching file LuaJIT-2.1-20190507/src/lj_arch.h
patching file LuaJIT-2.1-20190507/src/lj_cconv.c
patching file LuaJIT-2.1-20190507/src/lj_obj.h
patching file LuaJIT-2.1-20190507/src/lj_state.c
patching file lua-resty-core-0.1.17/lib/resty/core/socket_tcp.lua
patching file lua-resty-core-0.1.17/lib/resty/core/socket_tcp.lua
patching file lua-resty-core-0.1.17/lib/resty/core/socket_tcp.lua
patching file lua-resty-core-0.1.17/lib/resty/core/socket_tcp.lua
patching file lua-resty-core-0.1.17/lib/resty/core/socket_tcp.lua
patching file lua-resty-core-0.1.17/lib/resty/core.lua
patching file …
```
=> chore(patches) make 1.15.8.3 patches to apply cleanly

openresty-patches/patches/1.17.8.1/LuaJIT-2.1-20200102_01-dyn-lightuserdata-map.patch, openresty-patches/patches/1.17.8.1/lua-resty-core-0.1.19_01-cosocket-mtls.patch, openresty-patches/patches/1.17.8.1/lua-resty-core-0.1.19_03-upstream_recreate_request.patch, openresty-patches/patches/1.17.8.1/nginx-1.17.8_01-upstream_client_certificate_and_ssl_verify.patch, openresty-patches/patches/1.17.8.1/ngx_stream_lua-0.0.8_01-inject-req-time-api.patch, openresty-patches/patches/1.17.8.2/LuaJIT-2.1-20200102_01-dyn-lightuserdata-map.patch, openresty-patches/patches/1.17.8.2/lua-resty-core-0.1.19_01-cosocket-mtls.patch, openresty-patches/patches/1.17.8.2/lua-resty-core-0.1.19_03-upstream_recreate_request.patch, openresty-patches/patches/1.17.8.2/nginx-1.17.8_01-upstream_client_certificate_and_ssl_verify.patch, openresty-patches/patches/1.17.8.2/ngx_stream_lua-0.0.8_01-inject-req-time-api.patch
```
patching file LuaJIT-2.1-20200102/src/lj_api.c
patching file LuaJIT-2.1-20200102/src/lj_arch.h
Hunk #1 succeeded at 241 (offset 4 lines).
patching file LuaJIT-2.1-20200102/src/lj_cconv.c
patching file LuaJIT-2.1-20200102/src/lj_obj.h
Hunk #1 succeeded at 831 (offset 1 line).
patching file LuaJIT-2.1-20200102/src/lj_state.c
patching file lua-resty-core-0.1.19/lib/resty/core/socket_tcp.lua
patching file lua-resty-core-0.1.19/lib/resty/core/socket_tcp.lua
patching file lua-resty-core-0.1.19/lib/resty/core/socket_tcp.lua
patching file lua-resty-core-0.1.19/lib/resty/core/socket_tcp.lua
patching file lua-resty-core-0.1.19/lib/resty/core/socket_tcp.lua
patching file lua-resty-core-0.1.19/lib/resty/core.lua
Hunk #1 succeeded at 19 with fuzz 1 (offset -2 lines).
patching file …
```
=> chore(patches) make 1.17.8.1 and 1.17.8.2 patches to apply cleanly

openresty-patches/patches/1.15.8.3/ngx_stream_lua-0.0.7_04-ffi_crc32_api.patch
Adds missing patch in the family of:
* ngx_lua-0.10.15_03-ffi_crc32_api.patch
* lua-resty-core-0.1.17_05-ffi_crc32_api.patch
=> feat(openresty-patches) add ngx_stream_lua-0.0.7_04-ffi_crc32_api.patch

Jenkinsfile, build-kong.sh
The following PR https://github.com/Kong/kong/pull/6361/files per
should have upgraded both lua-resty-worker-events and lua-resty-healthcheck but fails.
I believe this design is correct / safe but as a result we should make sure the openresty container we build our test container on top of doesn't have any installed luarocks
=> fix(cache) utilize luarocks purge --old-versions to keep our luarocks current

test/Dockerfile.test
when we only pin the major/minor of a luarock ie `~1.1` when the luarock releases a new patch `1.1.5` we need to ensure the new version gets installed.
I believe we can/should resolve this using [luarocks dependency locking ](https://github.com/luarocks/luarocks/blob/master/CHANGELOG.md#whats-new-in-luarocks-330) such that after running `make dev` one is fully up to date. Until then this effectively purges / reinstalls all `luarocks`
=> fix: remove / reinstall luarocks to make sure we catch version bumps

.dockerignore, test/Dockerfile.test
Explicitly set `GOPATH` and `GOROOT` to different directories; while the former is the Go development workspace, the latter carries the Go SDK; previously, errors like `cannot download, $GOPATH must not be set to $GOROOT` would occur when building in GOPATH mode.
=> fix(tests) go path

openresty-patches/patches/1.17.8.1/resty-cli-0.25-fix_tmp_directory_deletion.patch, openresty-patches/patches/1.17.8.2/resty-cli-0.25-fix_tmp_directory_deletion.patch
resty-cli does not properly delete `/tmp/resty_*` directories. This is only required for OpenResty versions 1.17.8.x due to the use of resty-cli v0.25; v0.26 fixed the issue and has been made available in later versions of OpenResty.
Related: https://github.com/openresty/resty-cli/pull/58
=> feat(openresty-patches) add patch to fix resty-cli; delete /tmp dirs

openresty-patches/patches/1.17.8.2/ngx_lua-0.10.17_04-balancer_buffer.patch
Contains the patch from https://github.com/openresty/lua-nginx-module/commit/97b91899c996a459c88d313a0151663369525627
=> feat(openresty-patches) add balancer buffer patch

openresty-build-tools/kong-ngx-build
We need to use the latest lua-resty-dns which is not yet released. This PR overwrites the one bundled in OpenResty with the (currently) latest, using the commit SHA hash.
=> chore(kong-ngx-build) use newer lua-resty-dns

openresty-build-tools/kong-ngx-build
With the new `luarocks` version available (3.7.0) it is not currently uploaded to luarocks.org. Since it is available on GitHub this adds the ability to provide a failover for the source download.
=> feat(build) allow failover download of luarocks source from GH

Jenkinsfile
Kong no longer uses the next branch. All PRs are merged into
master.
=> chore(ci) change default kong branch to master

test/Dockerfile.test
used for building go-pluginserver and vegeta
=> chore(tests) bump go version used in kong tests

test/tests/01-package/run.sh
Add a `systectl status kong` so when kong fails on the systemctl test we know why without reproducing it locally
=> test(systemd) add some verbosity to the systemd tests so we know why it fails

docker-compose.yml, test/kong-tests-compose.yaml
Postgres 9.5 is 5 years old and EOL already:
https://www.postgresql.org/support/versioning/
Approve but do not merge until after 2.4 GA.
=> chore(postgres) bump test Postgres version to 13

openresty-build-tools/kong-ngx-build
Chaining these actions with `&&` made the `rm -rf` never occur in MacOS.
The `--keep-newer-files` option was making `tar` uncompress the files,
but it was also generating warnings and eventually exiting with a non-0
status.
As a result the .tar.gz file was never removed. When openresty tries to
process lua-resty-dns it got confused by the .tar.gz and would error
with "Multiple entries for lua-resty-dns".
=> fix(openresty-build-tools) remove lua-resty-dns .tar.gz in MacOS

openresty-build-tools/kong-ngx-build
It appears that ftp.pcre.org is no longer online and the
[official website for PCRE](http://pcre.org) now recommends downloading from the SourceForge mirror
instead.
=> fix(kong-ngx-build) use SourceForge mirror for PCRE downloads

openresty-patches/patches/1.19.9.1/LuaJIT-2.1-20210510_01-ffi-arm64-macos-fix-vararg-call-handling.patch, openresty-patches/patches/1.19.9.1/LuaJIT-2.1-20210510_02-arm64-fix-pcall-error-case.patch, openresty-patches/patches/1.19.9.1/lua-resty-core-0.1.22_03-make-resty.core.shdict-compatible-with-m1.patch, openresty-patches/patches/1.19.9.1/lua-resty-core-0.1.22_04-make-resty.core.response-compatible-with-m1.patch
This is related to:
https://github.com/Kong/kong/pull/8202
The C `open` is variadic and causes issues with M1. So one patch was included for that. The other patch is for pcall which seemed to be reasonable to include as well.
PS. I tried latest LuaJIT and OpenResty `master` branches as well, but they caused issues.
=> chore(patches) handpicked a couple of LuaJIT patches needed for macOS+M1

.gitignore
Adding `openresty-build-tools/build` in `.gitignore`.
=> fix: adding openresty-build-tools/build folder in .gitignore

openresty-build-tools/kong-ngx-build
This adds a flag to the `openresty` build script entitled: `--download-extract-only`: the purpose of which is to seed the download cache with the various source archives this script collects, and exiting early to avoid also compiling those sources.
Subsequent runs of this script, assuming `--work`/`$DOWNLOAD_CACHE` is the same, will avoid re-download/extracting said files via the numerous `test -d` `if/then/fi` checks that already exist here.
Ideally, this would have been solely a `--download-only` flag but the current structure of the script doesn't lend itself to early termination/return (as it place entirely within a single `main()` function).
=> feat(dl): add --download-extract-only flag

build-openresty.sh
Reasoning for this change: we need to be able to build lmdb directly
fron kong-build-tools Makefile.
Currently the process is:
* The Makefile initializes RESTY_LMDB with the contents of kong's
.requirements file, or empty string otherwise
* `make build-kong` calls `make build-openresty`
* `make build-openresty` will call
`docker build -f dockerfiles/Dockerfile.openresty`, passing
`--build-arg RESTY_LMDB`
* The dockerfile copies `build-openresty.sh` & `openresty-build-tools`
* `build-openresty.sh` gets called inside the docker image
* It calls openresty-build-tools, but it never passes --resty-lmdb
At this point, the lmdb build is "broken": there is no way to build lmdb
from the kbt makefile.
This change should make it possible to build lmdb from any kong repo
that RESTY_LMDB set on the …
=> fix(lmdb) pass --resty-lmdb in build-openresty.sh

dockerfiles/Dockerfile.openresty
Related with #434
Further testing has proved that the value of RESTY_LMDB was still not
passed around properly from the initial value set by this repo's
Makefile when it arrived to `openresty-build-tools`
The culprint seems to be that `RESTY_LMDB` was passed as a built-time
variable to the intermediate Docker image via the `--build-arg` option,
but _built-time variables are only available during ... build time. They
are *not* available during the actual running of the image.
In order to make them available during run time they must be:
* Declared as ARG variables on the Dockerfile, with an optional default
value if none was provided via --build-arg
* Used to initialize ENV variables
As shown on this PR.
Note that on this case the default value for the `ARG` is 0, so by default it
won't be …
=> fix(lmdb) make RESTY_LMDB build-time var into ENV

Makefile
Kong dependency cache:
We need to invalidate cache if:
- specific parts of kong-build-tools changed. What those parts are is fairly large in scope and the repository doesn't change "that" often so let's invalidate if any of it changes
- if any dependency version changes. These are tracked in kong.git:/.requirements so invalidate anytime that file changes
We also require a cache per architecture and per distribution at a minimum in some cases we need a cache between versions of a specific distribution.
Looking at the last X builds the majority of our releases missed the cache because of the cache busting. The cache busting intention was to capture breaking changes that happen in the larger ecosystem that we might not be aware of because of the cache. To my knowledge that's only happened …
=> feat(cache): the cache buster is one cause of why we have cache missed during a release

openresty-build-tools/kong-ngx-build
=> chore(boringssl) use gcc - FT-2342

openresty-patches/patches/1.19.9.1/lua-resty-core-0.1.22_01-cosocket-mtls.patch, openresty-patches/patches/1.19.9.1/lua-resty-websocket-0.08_01-client-mtls.patch, openresty-patches/patches/1.19.9.1/ngx_lua-0.10.20_01-cosocket-mtls.patch
This updates the mTLS patches for `ngx_lua` and `lua-resty-core`, to reflect the latest commits [here](https://github.com/openresty/lua-nginx-module/pull/1602) and [here](https://github.com/openresty/lua-resty-core/pull/278).
This is provisional for now as further updates may be made.
=> feat(openresty-patches) update mtls cosocket patches

test/Dockerfile.test
_leaving the Make task and Dockerfile behind in case someone somewhere is still using this. Removing it would be a breaking change and should be approached with more care than this PR which is to unblock us_
=> fix(go): This is broken but I believe it's no longer used so let's remove it refs: #ENGEN-476

kong.logrotate
=> fix(logrotate) add `delaycompress` option to fix zip compression error

Makefile, build-openresty.sh, dockerfiles/Dockerfile.openresty, openresty-build-tools/kong-ngx-build, test/tests/01-package/run.sh
This adds [Kong's fork of lua-resty-websocket](https://github.com/Kong/lua-resty-websocket]) to kong-ngx-build.
Main differences between our fork and the current lua-resty-websocket release (v0.08) are:
* mTLS support for `client:connect()` - this has been [merged](https://github.com/openresty/lua-resty-websocket/pull/72) but is not yet released
* other `client:connect()`  enhancements - features needed by Kong that we'll attempt to upstream as best we can ([example](https://github.com/openresty/lua-resty-websocket/pull/76))
Full diff:
https://github.com/openresty/lua-resty-websocket/compare/v0.08...Kong:master
This affects CE and EE as both rely on the mTLS functionality. Up until now this has been achieved by way of [patch file](https://github.com/Kong/kong-build-tools/blob/886101503c3bc …
=> feat(openresty) bundle Kong/lua-resty-websocket

Jenkinsfile, Makefile, release-kong.sh
While testing https://github.com/Kong/kong-ee/pull/3093 it was found we haven't captured the way Kong Enterprise expects internal releases to work.
**Kong Enterprise pre-releases go to the production release environment in a private location**
1. When the git tag has a `-` the Kong EE Makefile sets `OFFICIAL_RELEASE=false` ( https://github.com/Kong/kong-ee/blob/a65e715f0aa128202dd98246006522d8dd52f294/Makefile#L65-L68 )
2. If we're ENTERPRISE=true && OFFICIAL_RELEASE=false set the release flag to `--internal` ( https://github.com/Kong/kong-build-tools/blob/d9d008e2c8212c0cf76402693597e396325025c7/release-kong.sh#L112-L117 )
**Kong CE pre-releases go to the staging release environment in a public location**
1. Kong CE Jenkinsfile sets PULP_HOST_STAGE and PULP_HOST_PROD whereas EE's …
=> feat(releases): add capability of doing ee internal releases

Jenkinsfile, test/build_container.sh
a series of conflating PR reviews led us to accidentally drop tests for the alpine arm asset and then break our ability to run tests when doing multi-architecture alpine builds.
This fixes the CI so it once again tests the alpine arm64 and also the necessary differentiation the build test image requires to distinguish when there's a amd and an arm asset.
Example of the failure: https://internal.builds.konghq.com/blue/organizations/jenkins/kong/detail/master/3/pipeline#step-37-log-2432
=> fix(alpine): alpine needs to specify the arm64 architecture

Makefile
The notable exception to this are the Makefile vars like: `DOCKER_MACHINE_ARM64_NAME?=docker-machine-arm64-${USER}` that utilize curly braces-- those will only appear "expanded".
Previously:
```
$ gmake debug
starting make in kong-build-tools
kong/kong-build-tools
true
false
true
docker pull
docker push
docker build --progress=auto --build-arg BUILDPLATFORM=x/amd64
0
0.2.1
master
2.8.0
kong
true
```
Now:
```
$ gmake debug
starting make in kong-build-tools
.SHELLSTATUS = 0
BUILDX = false
BUILDX_INFO =
BUILDX_INFO =
BUILD_TOOLS_SHA = $(git rev-parse --short HEAD)
BUILD_TOOLS_SHA = acec034
CACHE = true
CACHE_BUSTER = 0
DEBUG = 0
DOCKER_BASE_SUFFIX = $(git rev-parse --short HEAD)0
DOCKER_BASE_SUFFIX = acec0340
DOCKER_BUILD_PROGRESS = auto
DOCKER_KONG_SUFFIX = $(git rev-parse --short …
```
=> feat(make) improve debug output

build-kong.sh
tested as follows:
```
make package-kong
dpkg -c output/kong-2.8.0.20.04.amd64.deb | grep wrpc.proto
-rw-r----- 0/0            6271 2022-05-23 13:21 ./usr/local/kong/lib/include/wrpc/wrpc.proto
```
a backwards compatible tests would be a quick smoke of running hybrid Kong that I don't have the bandwidth to take on but it's on the todo list
=> fix(hybrid): fix the path to the wrpc file

openresty-build-tools/kong-ngx-build, openresty-patches/patches/1.19.9.1/LuaJIT-2.1-20210510_03_patch_macro_luajit_version.patch, openresty-patches/patches/1.21.4.1/LuaJIT-2.1-20210510_01_patch_macro_luajit_version.patch, test/tests/01-package/run.sh
This is one solution to fix `FT-2807`. Another solution is https://github.com/Kong/kong-build-tools/pull/466 .
```
$ resty -e "print(jit.version)"
LuaJIT 2.1.0-20210510
```
=> feat(LuaJIT) change the LuaJIT version format to something like `LuaJIT 2.1-20220411`

Makefile, test/build_container.sh
This caused the `pushd docker-kong` to go to that folder rather than the locally cloned one. I also added some logging I found helpful.
=> I have docker-kong checked out locally and on my CDPATH 

Jenkinsfile, release-kong.sh, test/build_container.sh
existing: if alpine we push `kong:x.y.z` and `kong:latest`
new behaviour: if `RELEASE_DOCKER=true` we push `kong:x.y.z-dist`
also when the base image is debian we use a slim debian
=> feat(release): use an explicit environment variable to determine when to push docker images

Makefile, dockerfiles/Dockerfile.openresty
utilize docker buildkit `--cache-from` so we get higher fidelity than our current cache hit which is either the entire image already exists or it does not
Before
After
=> feat(cache-from): use docker buildkit cache-from ability

.releaserc, Jenkinsfile
Using the prior art from https://github.com/Kong/template-generic which is in use on we want conventional commit releases not angular and we make our release rules less restrictive.
This also makes the adjustment so every commit to master runs the release logic
=> fix(release): adjust release logic from angular to conventionalCommit

.github/workflows/release.yaml, .releaserc, Jenkinsfile
Tested as viable on my fork https://github.com/hutchic/kong-build-tools/runs/6834563325?check_suite_focus=true
Changing the commit analyzer might lead to an unexpected jump in our semver but I think that's OK
=> chore(ci): use github actions for release purposes

.releaserc, Makefile
We desire the ability to have a more local faster cache in places. To avoid side effects of overlapping cache's that may or may not hit / refresh on different requirements let's share a central unified authoritative cache key from one place.
An example of the cache key in use https://github.com/Kong/kong-ee/pull/3322/commits/866f3b18ff9b949b0b733e755c920ca8ccfc6b95
=> chore(ci): add kong-ci-cache-key

Jenkinsfile, test/build_container.sh, test/tests/01-package/run.sh
Full RedHat family versions are classically 2 digits (`7.9`, `8.6`, `9.0`) and the ubi docker container image tags conform to that standard:
- [registry.access.redhat.com/ubi7/ubi-minimal:7.9](https://catalog.redhat.com/software/containers/ubi7/ubi-minimal/5c3594f7dd19c775cddfa777?tag=all)
- [registry.access.redhat.com/ubi7/ubi-minimal:8.6](https://catalog.redhat.com/software/containers/ubi8/5c647760bed8bd28d0e38f9f?tag=all)
- [redhat/ubi9:9.0](https://hub.docker.com/r/redhat/ubi9/tags)
Crucially, they do NOT offer "major-only" floating tags (e.g. `*:9`).
This PR just splits out the major version of the `RESTY_IMAGE_TAG`.
=> fix(rhel): allow RESTY_IMAGE_TAG to be 2+ digits

.github/workflows/release.yaml, .releaserc, Makefile, release-kong.sh, test/build_container.sh
kong-ee migrated from `make release` to `make package-kong && make build-test-container`. This led to breaking gojira because the resulting image lacked some labels.
This PR applies the label to build-test-container and makes it consistent across all docker images
Sample failure: https://github.com/Kong/kong-ee/runs/7288776241?check_suite_focus=true
=> fix(docker): consistent docker image labels

openresty-build-tools/kong-ngx-build
This updates kbt to respect the `CARGO_HOME` env var if it's defined. See the [cargo docs](https://doc.rust-lang.org/cargo/reference/environment-variables.html?highlight=CARGO_HOME#environment-variables-cargo-reads)  for more info on this variable.
=> fix(kong-ngx-build): respect CARGO_HOME when building

Makefile, release-kong.sh
We made the decision to support 4 digits in Kong EE (`3.0.0.0`) until
we finish the Unified Data Plane work. I have tested these changes
locally.
Codependent with https://github.com/Kong/kong-ee/pull/3431
Signed-off-by: Tyler Ball <tyler.ball@konghq.com>
=> feat(enterprise): Restoring the 4th digit of the Kong EE version

kong.logrotate
The rpm installation of Kong 2.2.0 start using a self-created kong user as the o
wner for /usr/local/kong/logs instead of system nobody. But the directory's perm
issions allow writes by a group that isn’t root are not permitted by Logrotate,
or you may see the error as "insecure permissions".
The idea of this PR is to fix the warning errors when running logrotate.
FTI-3197
=> fix(logrotate): add `su kong kong` to avoid logrotate warnings

Makefile, release-kong.sh
The [make task](https://github.com/Kong/kong-build-tools/blob/master/Makefile#L334-L351) that handles releasing docker images is cleaner (and works). Swap out to using it exclusively
=> fix(release): unify the docker release logic to one spot

.releaserc
No idea why the semantic release action started needing this.
~ https://github.com/Kong/kong-build-tools/runs/8280394112?check_suite_focus=true
```
[11:56:06 PM] [semantic-release] › ℹ  Running semantic-release version 19.0.5
[11:56:07 PM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/github"
[11:56:07 PM] [semantic-release] › ✔  Loaded plugin "analyzeCommits" from "@semantic-release/commit-analyzer"
[11:56:07 PM] [semantic-release] › ✔  Loaded plugin "generateNotes" from "@semantic-release/release-notes-generator"
[11:56:07 PM] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/github"
[11:56:07 PM] [semantic-release] › ✔  Loaded plugin "addChannel" from "@semantic-release/github"
[11:56:07 PM] [semantic-release] › ✔  Loaded plugin …
```
=> fix(releaserc): Explicitly Define repositoryUrl

.github/workflows/release.yaml
The last known good version of this github action.
Worked as recently as: https://github.com/Kong/kong-build-tools/runs/8117001411?check_suite_focus=true#step:4:7
=> fix(releaserc): revert to sr 19.0.2

test/build_container.sh
Looking at https://catalog.redhat.com/software/containers/search it looks like all the different rhel distributions are at a top level name in the Red Hat registry, IE
registry.access.redhat.com/ubi7
registry.access.redhat.com/ubi8
registry.access.redhat.com/ubi8-minimal
I'm not sure where the 2nd part of the package name came from in the original sed.
Signed-off-by: Tyler Ball <tyler.ball@konghq.com>
=> fix(release) Use the correct redhat docker registry format

openresty-build-tools/kong-ngx-build
Needed to allow 3.0+ `kong-ngx-build` to run in the kong homebrew formula/tap: https://github.com/Kong/homebrew-kong/pull/204
(Where rust/cargo is supplied by homebrew.)
=> fix(ngx-build): allow cargo in homebrew-kong

openresty-build-tools/kong-ngx-build
The previous strategy of trying to load the env script unconditionally failed if the script did not exist, despite the '|| true' that was there to avoid that.
=> fix(ngx-build): only try to load env script when cargo is not found

.ci/setup_ci.sh
So as to avoid `sudo apt-get install -y qemu binfmt-support qemu-user-static` on MacOS,
=> fix(ci): skip setup on Mac OS

Makefile
Introduced a bug [here](https://github.com/Kong/kong-build-tools/commit/86e23c347b392d5c01bb8cfd2fdab2ba0e02d8c1#diff-74722fe522ae11801a3294458893ab7ea513c4b899d4ff9089d3a849caf9f50bR8) when we adapted kong-build-tools to use qemu for packaging our multi-architecture images.
adjusted to build `$ARCHITECTURE-$KONG_TEST_CONTAINER_TAG` instead of `$KONG_TEST_CONTAINER_TAG` but missed the cleanup step. Result is running two builds back to back we don't rebuild the subsequent test image
=> fix(cache): make sure we nuke the architecture specific image refs: #FTI-4339

Jenkinsfile
Reverts Kong/kong-build-tools#558
Adding back RHEL/Centos 7 because of FTI-4454
=> Revert "fix(*) drop RHEL 7"

.gitignore, Makefile, dockerfiles/Dockerfile.kong, dockerfiles/Dockerfile.openresty
Instead of relying on a private docker hub repository to gate access to the GITHUB_TOKEN getting baked into the docker images utilise docker buildkit secret file to inject the token
=> fix(security): migrate GITHUB_TOKEN to a buildkit secret file

Makefile, dockerfiles/Dockerfile.openresty
libyaml has been moved to the [base image](https://github.com/Kong/kong-build-tools-base-images/pull/61)
=> chore(yaml): libyaml was moved to the base images

Makefile
Should resolve the current silent failure:
```
Pull an image or a repository from a registry
/bin/bash: line 4: kong/kong-build-tools:deb-1.6.1: No such file or directory
/bin/bash: line 5: kong/kong-build-tools:rpm-1.6.1: No such file or directory
/bin/bash: line 6: deb: command not found
```
By making the `docker pull ...` command aware of the recent changes to `Dockerfile.openresty`.
=> fix(make): account for FROM .. AS dockerfile.or

fpm-entrypoint.sh
Fixes an issue where the 3.x yum/rpm repos were installing (CE) kong when asked to install `kong-enterprise-edition`.
=> fix(packaging): we don't want Kong to replace kong-enterprise-edition refs: #INC-155

openresty-build-tools/kong-ngx-build
This pull request adds `--with-http_sub_module` to OpenResty's build options to enable the `ngx_http_sub_module` for https://github.com/Kong/kong-ee/pull/3945.
FTI-976
=> feat(openresty): enable ngx_http_sub_module

dockerfiles/Dockerfile.package, test/tests/01-package/run.sh
I think both of these PR's merged prematurely as they were both failing and are now failing on master.
- The kong/fpm failure is unexpected and will need to investigate why rpm signing is failing
- The openssl is linked / loadable has been failing on Kong alpine and gateway engineers need to resolve this
=> chore(revert)

Makefile
Previously, the `debug` make target didn't display ENVs that existed in the environment, or make default variables, before make ran because `VARS_OLD := $(.VARIABLES)` naively includes all existing ENVs and default make variables.
Now, the debug make target will inspect this makefile itself using `make -pn ...` to get a more complete list of variables (make + environment).
This PR also fixes a minor bug where an ENV that had a semicolon in it wouldn't be displayed properly:
```
$ export COLORFGBG='15;0'
$ make debug
...
/bin/bash: 0: command not found
COLORFGBG = 15;0
COLORFGBG = 15
...
```
=> chore(make): include pre-make ENVs in debug

openresty-patches/patches/1.21.4.1/LuaJIT-2.1-20220411_02.patch
There is a wrong offset in patch, so it complains about it with a notice:
```
patching file LuaJIT-2.1-20220411/src/lj_record.c
patch unexpectedly ends in middle of line
Hunk #1 succeeded at 2566 with fuzz 1 (offset -6 lines).
```
This commit fixes the offset.
=> fix(patches) apply luajit patch cleanly

openresty-build-tools/kong-ngx-build, test/tests/01-package/run.sh
Ensure boringssl headers are included in packages - which is already done for openssl and required by LuaSec.
FT-3384
=> feat(build) include boringssl headers in final distro

fpm-entrypoint.sh
Tested locally.
```
export PACKAGE_TYPE=rpm RESTY_IMAGE_BASE=rhel RESTY_IMAGE_TAG=8.6
make package-kong
... snip ...
ls output 
kong-3.1.0.rhel8.amd64.rpm
```
=> fix(rhel): drop the last digit on rhel naming
