Kong/kong-build-tools

.travis.yml
Makefile

just a copy-pasta from `travis.yml` into `Makefile`

fix(tests) move test setup out of travis.yml into Makefile

---

.travis.yml
Makefile
README.md
test/run_tests.sh
test/test_smoke.tavern.yaml

Adjust how the tests are ran so they can more easily be ran in isolation so other Kong CI/CD can use the functional tests

feat(ci) adjust so running the functional test can be ran isolated

---

entrypoint.sh
test/run_tests.sh

Also added a test to validate the `luarocks` command succeeds in the release assets

fix(lua) sed the luapaths so they don't reference `/tmp/build`

---

renovate.json

try the solution as directed per https://github.com/renovatebot/config-help/issues/216

chore(renovate) dont ignore test directory

---

kube-registry.yaml
test/run_tests.sh

use a local yaml file to define the k8s docker registry

fix(tests) k8s registry

---

renovate.json

The PR to configure renovate for only the weekends passed not sure why it's not OK anymore

chore(ci) reconfigure renovate scheduling

---

.ci/setup_ci.sh
.travis.yml
Makefile
kind-config.yaml
test/run_tests.sh

replace minikube with kind.
Is a lighter touch single host docker option. minikube has been challenging to keep everything pinned and working reliably

fix(tests) switch from minikube to kind

---

openresty-build-tools/openresty-patches/patches/1.15.8.2/lua-resty-core-0.1.17_03-cosocket-mtls.patch
openresty-build-tools/openresty-patches/patches/1.15.8.2/lua-resty-websocket-0.07_01-client-mtls.patch
openresty-build-tools/openresty-patches/patches/1.15.8.2/ngx_lua-0.10.15_04-cosocket-mtls.patch

Copied from https://github.com/Kong/openresty-patches/pull/57

feat(openresty-patches) add cosocket mTLS handshake patches

---

Dockerfile.test
Jenkinsfile
Makefile

capable of running the Kong unit tests that require the go library.
Eventually need to de-duplicate some logic but this works for now

test(go) go Kong unit tests

---

test/tests/01-package/run.sh

adjusting the Kong docker containers to run as a Kong user requires this change

test(user) set the default docker user to root for tests

---

kong.service
test/run_tests.sh
test/tests/01-package/run.sh

added a test and fixed the broken systemctl command

fix(systemctl) fixes systemctl reload kong.service

---

Makefile

only push images to our shared cache if the tests pass

fix(cache) push if successful

---

openresty-patches/patches/1.15.8.3/lua-resty-core-0.1.17_02-dyn_upstream_keepalive.patch
openresty-patches/patches/1.15.8.3/ngx_lua-0.10.15_02-dyn_upstream_keepalive.patch
openresty-patches/patches/1.15.8.3/ngx_lua-0.10.15_03-ffi_crc32_api.patch

Sibling PR for https://github.com/Kong/kong/pull/5771

feat(openresty-patches) add dynamic upstream keepalive pool patches

---

Makefile
build-openresty.sh
dockerfiles/Dockerfile.openresty

feat(nginx-module) add the ability to pin the kong nginx module

---

Jenkinsfile

made a new jenkins worker type. It's based on bionic and using spot on-demand instances

chore(ci) swap to ubuntu bionic jenkins worker

---

test/build_container.sh

adjust to match https://github.com/Kong/docker-kong/pull/380

chore(docker) fix kong-build-tools w\ docker-kong compatibility

---

openresty-patches/patches/1.15.8.3/lua-resty-core-0.1.17_04-hash_stream_subsystem.patch
openresty-patches/patches/1.15.8.3/lua-resty-core-0.1.17_05-ffi_crc32_api.patch
openresty-patches/patches/1.17.8.1/LuaJIT-2.1-20200102_01-dyn-lightuserdata-map.patch
openresty-patches/patches/1.17.8.1/lua-resty-core-0.1.19_01-cosocket-mtls.patch
openresty-patches/patches/1.17.8.1/lua-resty-core-0.1.19_02-dyn_upstream_keepalive.patch
openresty-patches/patches/1.17.8.1/lua-resty-core-0.1.19_03-upstream_recreate_request.patch
openresty-patches/patches/1.17.8.1/lua-resty-core-0.1.19_04-stream_req_start_time.patch
openresty-patches/patches/1.17.8.1/lua-resty-websocket-0.07_01-client-mtls.patch
openresty-patches/patches/1.17.8.1/nginx-1.17.8_01-upstream_client_certificate_and_ssl_verify.patch
openresty-patches/patches/1.17.8.1/nginx-1.17.8_02-remove-server-tokens-from-special-responses-output.patch
openresty-patches/patches/1.17.8.1/nginx-1.17.8_03-stream_proxy_ssl_disable.patch
openresty-patches/patches/1.17.8.1/ngx_lua-0.10.17_01-cosocket-mtls.patch
openresty-patches/patches/1.17.8.1/ngx_lua-0.10.17_02-dyn_upstream_keepalive.patch
openresty-patches/patches/1.17.8.1/ngx_lua-0.10.17_03-upstream_recreate_request.patch
openresty-patches/patches/1.17.8.1/ngx_stream_lua-0.0.8_01-inject-req-time-api.patch
openresty-patches/patches/1.17.8.1/ngx_stream_lua-0.0.8_02-expose_request_struct.patch
openresty-patches/patches/1.17.8.2/LuaJIT-2.1-20200102_01-dyn-lightuserdata-map.patch
openresty-patches/patches/1.17.8.2/lua-resty-core-0.1.19_01-cosocket-mtls.patch
openresty-patches/patches/1.17.8.2/lua-resty-core-0.1.19_02-dyn_upstream_keepalive.patch
openresty-patches/patches/1.17.8.2/lua-resty-core-0.1.19_03-upstream_recreate_request.patch
openresty-patches/patches/1.17.8.2/lua-resty-core-0.1.19_04-stream_req_start_time.patch
openresty-patches/patches/1.17.8.2/lua-resty-websocket-0.07_01-client-mtls.patch
openresty-patches/patches/1.17.8.2/nginx-1.17.8_01-upstream_client_certificate_and_ssl_verify.patch
openresty-patches/patches/1.17.8.2/nginx-1.17.8_02-remove-server-tokens-from-special-responses-output.patch
openresty-patches/patches/1.17.8.2/nginx-1.17.8_03-stream_proxy_ssl_disable.patch
openresty-patches/patches/1.17.8.2/ngx_lua-0.10.17_01-cosocket-mtls.patch
openresty-patches/patches/1.17.8.2/ngx_lua-0.10.17_02-dyn_upstream_keepalive.patch
openresty-patches/patches/1.17.8.2/ngx_lua-0.10.17_03-upstream_recreate_request.patch
openresty-patches/patches/1.17.8.2/ngx_stream_lua-0.0.8_01-inject-req-time-api.patch
openresty-patches/patches/1.17.8.2/ngx_stream_lua-0.0.8_02-expose_request_struct.patch

feat(openresty-patches) add patches for OpenResty 1.17.8.1

---

kong.service

Added `kong prepare` to the systemd reload file
fixes https://github.com/Kong/kong/issues/6271

fix(system) adjust systemd reload to do a kong prepare

---

fpm-entrypoint.sh

sample output we'll see in Jenkins going forward

chore(release) if we try to sign a package but fail we should fail

---

test/build_container.sh
test/tests/01-package/run.sh

depends on https://github.com/Kong/docker-kong/pull/438

fix(build) use correct base image for rhel8 tests

---

release-kong.sh

see https://github.com/opencontainers/image-spec/blob/master/annotations.md#pre-defined-annotation-keys

fix(image) fix typo in label name

---

test/Dockerfile.test

Add the `vegeta` tool to the test environment.

chore(test) install vegeta for stress tests

---

openresty-patches/README.md
openresty-patches/patches/1.19.3.1/lua-resty-core-0.1.21_01-cosocket-mtls.patch
openresty-patches/patches/1.19.3.1/lua-resty-core-0.1.21_02-dyn_upstream_keepalive.patch
openresty-patches/patches/1.19.3.1/lua-resty-websocket-0.08_01-client-mtls.patch
openresty-patches/patches/1.19.3.1/nginx-1.19.3_01-upstream_client_certificate_and_ssl_verify.patch
openresty-patches/patches/1.19.3.1/nginx-1.19.3_02-remove-server-tokens-from-special-responses-output.patch
openresty-patches/patches/1.19.3.1/nginx-1.19.3_03-stream_proxy_ssl_disable.patch
openresty-patches/patches/1.19.3.1/nginx-1.19.3_04-grpc_authority_override.patch
openresty-patches/patches/1.19.3.1/ngx_lua-0.10.19_01-cosocket-mtls.patch
openresty-patches/patches/1.19.3.1/ngx_lua-0.10.19_02-dyn_upstream_keepalive.patch
openresty-patches/patches/1.19.3.1/ngx_stream_lua-0.0.9_01-expose_request_struct.patch

Adds adjusted Kong patches for OpenResty 1.19.3.1 release.

chore(patches) add kong patches for openresty 1.19.3.1

---

openresty-patches/patches/1.19.3.1/ngx_lua-0.10.19_03-closed_listener_fd.patch

Contains the patch from https://github.com/openresty/lua-nginx-module/pull/1832

feat(openresty-patches) add closed listener's fd patch

---

Jenkinsfile

Replace existing token with a bot token.

chore(ci) update github token

---

dockerfiles/Dockerfile.openresty
openresty-patches/README.md
openresty-patches/patches/1.19.3.2/lua-resty-core-0.1.21_01-cosocket-mtls.patch
openresty-patches/patches/1.19.3.2/lua-resty-core-0.1.21_02-dyn_upstream_keepalive.patch
openresty-patches/patches/1.19.3.2/lua-resty-websocket-0.08_01-client-mtls.patch
openresty-patches/patches/1.19.3.2/nginx-1.19.3_01-upstream_client_certificate_and_ssl_verify.patch
openresty-patches/patches/1.19.3.2/nginx-1.19.3_02-remove-server-tokens-from-special-responses-output.patch
openresty-patches/patches/1.19.3.2/nginx-1.19.3_03-stream_proxy_ssl_disable.patch
openresty-patches/patches/1.19.3.2/nginx-1.19.3_04-grpc_authority_override.patch
openresty-patches/patches/1.19.3.2/ngx_lua-0.10.19_01-cosocket-mtls.patch
openresty-patches/patches/1.19.3.2/ngx_lua-0.10.19_02-dyn_upstream_keepalive.patch
openresty-patches/patches/1.19.3.2/ngx_lua-0.10.19_03-closed_listener_fd.patch
openresty-patches/patches/1.19.3.2/ngx_stream_lua-0.0.9_01-expose_request_struct.patch

Adds Kong patches for OpenResty 1.19.3.2 release.

chore(patches) add kong patches for openresty 1.19.3.2

---

openresty-patches/README.md
openresty-patches/patches/1.19.3.2/nginx-1.19.3_05-remove-server-headers-from-ngx-header-filter-module.patch

Fix https://github.com/Kong/kong/issues/7183

feat(patches) remove nginx/openresty server header

---

dockerfiles/Dockerfile.openresty
openresty-patches/README.md
openresty-patches/patches/1.19.9.1/lua-resty-core-0.1.22_01-cosocket-mtls.patch
openresty-patches/patches/1.19.9.1/lua-resty-core-0.1.22_02-dyn_upstream_keepalive.patch
openresty-patches/patches/1.19.9.1/lua-resty-websocket-0.08_01-client-mtls.patch
openresty-patches/patches/1.19.9.1/nginx-1.19.9_01-upstream_client_certificate_and_ssl_verify.patch
openresty-patches/patches/1.19.9.1/nginx-1.19.9_02-remove-server-tokens-from-special-responses-output.patch
openresty-patches/patches/1.19.9.1/nginx-1.19.9_03-stream_proxy_ssl_disable.patch
openresty-patches/patches/1.19.9.1/nginx-1.19.9_04-grpc_authority_override.patch
openresty-patches/patches/1.19.9.1/nginx-1.19.9_05-remove-server-headers-from-ngx-header-filter-module.patch
openresty-patches/patches/1.19.9.1/ngx_lua-0.10.20_01-cosocket-mtls.patch
openresty-patches/patches/1.19.9.1/ngx_lua-0.10.20_02-dyn_upstream_keepalive.patch
openresty-patches/patches/1.19.9.1/ngx_stream_lua-0.0.10_01-expose_request_struct.patch

Adds patches to latest OpenResty release 1.19.9.1.

feat(patches) add openresty 1.19.9.1 patches

---

Jenkinsfile
README.md
test/build_container.sh

Removes references to both Debian 8 "jessie".

[ENGEN-450] chore(debian): remove EOLed 8

---

build-kong.sh

Sister change to: https://github.com/Kong/kong-distributions/pull/774

fix(analytics): cp proto definition folder

---

test/util.sh

sniping the test improvements from https://github.com/Kong/kong-build-tools/pull/452

fix(tests): adjust how we determine if Kong is ready to be more stable

---

test/tests/01-package/run.sh

BREAKING CHANGE: adjust Kong file ownership from kong:kong to kong:root

fix(package) tests for kong:kong -> kong:root

---

dockerfiles/Dockerfile.openresty
openresty-patches/README.md
openresty-patches/patches/1.21.4.1/lua-cjson-2.1.0.10_01-empty_array.patch
openresty-patches/patches/1.21.4.1/lua-resty-core-0.1.23_01-cosocket-mtls.patch
openresty-patches/patches/1.21.4.1/lua-resty-core-0.1.23_02-dyn_upstream_keepalive.patch
openresty-patches/patches/1.21.4.1/lua-resty-core-0.1.23_03-make-resty.core.shdict-compatible-with-m1.patch
openresty-patches/patches/1.21.4.1/lua-resty-core-0.1.23_04-make-resty.core.response-compatible-with-m1.patch
openresty-patches/patches/1.21.4.1/lua-resty-websocket-0.09_01-client-mtls.patch
openresty-patches/patches/1.21.4.1/nginx-1.21.4_01-upstream_client_certificate_and_ssl_verify.patch
openresty-patches/patches/1.21.4.1/nginx-1.21.4_02-remove-server-tokens-from-special-responses-output.patch
openresty-patches/patches/1.21.4.1/nginx-1.21.4_03-stream_proxy_ssl_disable.patch
openresty-patches/patches/1.21.4.1/nginx-1.21.4_04-grpc_authority_override.patch
openresty-patches/patches/1.21.4.1/nginx-1.21.4_05-remove-server-headers-from-ngx-header-filter-module.patch
openresty-patches/patches/1.21.4.1/ngx_lua-0.10.21_01-cosocket-mtls.patch
openresty-patches/patches/1.21.4.1/ngx_lua-0.10.21_02-dyn_upstream_keepalive.patch
openresty-patches/patches/1.21.4.1/ngx_stream_lua-0.0.11_01-expose_request_struct.patch

This commit adds support for OpenResty 1.21.4.1. Some patches were remove, and others were modified so that they apply cleanly.

feat(*) add openresty 1.21.4.1 patches

---

test/util.sh

Signed-off-by: Joshua Schmid <jaiks@posteo.de>

fix(tests): account for eventual consistency

---

build-kong.sh
test/tests/01-package/run.sh

A sister PR will open at Kong side

fix(proto) move all proto files to /usr/local/kong/include

---

test/util.sh

Ref: https://github.com/Kong/kong/commit/7dcbf9674bd2477811019a6a4ddf710fe5088bd6

fix(tests) test plugin existence instead of the value

---

Makefile
test/build_container.sh

This allows us to build a local image and use it with pongo

feat(enterprise): set org.opencontainers.image.revision for the test container

---

Makefile

Replaces https://github.com/Kong/kong-distributions/blob/master/package.sh#L553 which I think went missing when adapting kong-build-tools for kong-ee.
The docker-kong portions of this haven't changed (I don't think).
https://github.com/Kong/docker-kong/blob/94618439fa6f0cbcd057818848f0a5bba7dc170c/alpine/Dockerfile#L8

fix(ports): resupply EE_PORTS

---

Makefile
build-openresty.sh
dockerfiles/Dockerfile.openresty

- moved rust setup to [kong-build-tools-base-images](https://github.com/Kong/kong-build-tools-base-images/pull/54)
- display the build output of kong-ngx-build
- increased the arm build worker size

fix(ci): some tweaks to hopefully improve build speed

---

Makefile

Needs to get merged before https://github.com/Kong/kong-ee/pull/3826 will work

fix(make): pull kbt base imgs pre-OR build

---

Jenkinsfile

Reflect the product update for RHEL 7 sunset.
For FTI-4303, DOCU-2489

fix(*) drop RHEL 7

---

test/tests/01-package/run.sh

We have had some CI wonkiness where the `systemctl reload kong` package test fails due to an empty pid file:
> Oct 26 21:20:27 0f37d35f7c2e nginx[607]: nginx: [error] invalid PID number "" in "/usr/local/kong/pids/nginx.pid"
Seems like nginx was just taking slightly longer to start than expected, so I've made the following changes:
1. added a wait loop that will block until the nginx pidfile is non-empty (15s max). It should be a little more reliable than the prior approach of sleeping for 5s and continuing on.
2. pinned the worker process count to 2, as it should make for a consistently faster startup time.

tests(systemd): wait for nginx pidfile

---

after-install.sh
test/tests/01-package/run.sh

This also adds a comment (GEOOS field) to the Kong user.

fix(after-install) do not create home

---

build-kong.sh
dockerfiles/Dockerfile.kong
dockerfiles/Dockerfile.openresty
openresty-build-tools/common.sh
openresty-build-tools/kong-ngx-build
test/build_container.sh

cacheing the majority of these in a local asset store would be more ideal but until that takes place let's just retry with a wait

feat(retry): wrap everything that depends on external dependencies with a retry / backoff

---

Jenkinsfile
fpm-entrypoint.sh

related: https://github.com/amazonlinux/amazon-linux-2022/issues/182

feat(amazonlinux-2022): support and test amazonlinux 2022 refs: #FT-3480

---

openresty-build-tools/kong-ngx-build

to facilitate debugging memory issues

feat(kong-ngx-build): enable the no-pool patch in debug mode

---

Jenkinsfile
openresty-build-tools/kong-ngx-build

feat(boringssl) add a rhel-based boringssl package
